name: Jaime de Arcos - Blog
title: Jaime de Arcos - Blog
description: Jaime de Arcos development blog.
tags:
  - blog
  - developer
  - java
  - kotlin
  - spring
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
