name: Jaime's Blog
title: Jaime de Arcos - Blog
description: Jaime de Arcos development blog.
url: https://blog.jaimedearcos.com/
tags:
  - blog
  - developer
  - java
  - kotlin
  - spring
show_hero: true
menu:
  - title: Blog
    url: /
  - title: Home
    url: http://jaimedearcos.com/#/home
  - title: Works
    url: http://jaimedearcos.com/#/works
  - title: Contact
    url: http://jaimedearcos.com/#/contact
email: jaime.dearcos@gmail.com
disqus_username: blog-jaimedearcos
