name: Jaime's Blog
title: Jaime de Arcos - Blog
description: Jaime de Arcos development blog.
tags:
  - blog
  - developer
  - java
  - kotlin
  - spring
show_hero: true
menu:
  - title: Blog
    url: /
  - title: Works
    url: http://jaimedearcos.es/#/works
  - title: Contact
    url: http://jaimedearcos.es/#/contact
email: jaime.dearcos@gmail.com
disqus_username: blog-jaimedearcos
